# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c4c12023594cb12b28c35fc7ded93c1578245e649964e1708d393392520dbd132c46b66e5605b05e7339f0ffaaec0fc603a39f4c8a06fd78ec2afe12ae212d6

test:
  secret_key_base: 8a19164192be33bbd5a4e0aa921a5c9e9b7dc5fa6378ef3a78b91e6762bf0d6c5a5b55fff2b1a7904b07bad0e143eba1a91c794c830752bf7b532a7743f5fca1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
